export type MenuIDs =
  | 'preferences'
  | 'view-repository-on-github'
  | 'open-in-shell'
  | 'show-changes'
  | 'show-history'
  | 'show-repository-list'
  | 'open-working-directory'
  | 'show-repository-settings'
  | 'clone-repository'
  | 'about'
